# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
author: ETH CAMLab
name: 401-4656-21L AI in the Sciences and Engineering
title: AI in the Sciences and Engineering
email:
description: >
  401-4656-21L AI in the Sciences and Engineering - ETH ZÃ¼rich - HS2025
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.

url: https://camlab-ethz.github.io  # the base hostname & protocol for your site
baseurl: /ai4s_course # the subpath of your site, e.g. /blog/

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: camlab-ethz
google_analytics:
youtube_channel: 
rss:  # notes rss

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: Course Notes
blog_description: The notes written by students and edited by instructors

# Pagination
paginate: 10
permalink: /notes/:title/
paginate_path: /notes/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: # put your disqus shortname

# Optional features
show_social_icons:  true
enable_anchorjs:    true
enable_latexjs:     true
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  announcements:
    defaults:
      layout: post
    output: true
    permalink: /announcements/:path/

announcements_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: rouge

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jemoji

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.10.1"
anchorjs_version: "3.2.2"
latexjs_version: "0.11.1"

# theme removed to decouple from GitHub Pages default themes
